pretrained_model_path: "stabilityai/stable-diffusion-2-1-base"
checkpoint_dir: "methods/tuneavideo/checkpoints"

train_data:
  video_path: 
  prompt: 
  n_sample_frames: 24
  width: 512
  height: 512
  sample_start_idx: 0
  sample_frame_rate: 1


validation_data:
  video_length: 24
  width: 512
  height: 512
  num_inference_steps: 50
  guidance_scale: 4.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 10
validation_steps: 400
checkpointing_steps: 400
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True